<a href="https://colab.research.google.com/github/linlinzhang00923/linlinzhang00923.github.io/blob/main/AIDM7330_L6c_py_nb_pandas_stocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AIDM7330 Programming for Data Science

# Pandas

## Install Pandas package

In [ ]:
# Install required packages using pip package manager in the current Jupyter kernel
# Uncomment this code to run on your computer, no need on Google Colab

# import sys
# !{sys.executable} -m pip install pandas
# !{sys.executable} -m pip install matplotlib
# !{sys.executable} -m pip install seaborn

## Import Pandas

In [1]:
# import packages

import pandas as pd

# Extra packages
import numpy as np
import matplotlib.pyplot as plt # for plotting
import seaborn as sns # for plotting and styling

# Part 1 - Simple creation and manipulation of Pandas objects
**Key Points:** Pandas has two / three main data types:
* Series (similar to numpy arrays, but with index)
* DataFrames (table or spreadsheet with Series in the columns) [important!]
* Panels (3D version of DataFrame, not as common)

### A Series object in Pandas

Like an np.array, but we can combine data types and it has its own index

Note: Every column in a DataFrame is a Series

In [2]:
s = pd.Series([1,3,5,np.nan,6,8])  # sth. like a list; np.nan = missing data
print(s)
print(type(s))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
<class 'pandas.core.series.Series'>

In [3]:
s[3] # got index

np.float64(nan)

### A data frame object in Pandas

We use `pd.DataFrame(**parameters**)` and can insert almost any data type as an argument

**Function:** `pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)`

Input data can be a numpy ndarray (structured or homogeneous), Dictionary, List, or DataFrame.

In [4]:
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]

# Create the pandas DataFrame
df0 = pd.DataFrame(data, columns = ['Name', 'Age'])
df0

   Name  Age
0   tom   10
1  nick   15
2  juli   14

In [5]:
dictionary = {'label': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'value': [1, 2, 3, 4, 5, 6]}

df1 = pd.DataFrame(dictionary)
df1

  label  value
0     A      1
1     B      2
2     C      3
3     A      4
4     B      5
5     C      6

In [6]:
df1['label']

0    A
1    B
2    C
3    A
4    B
5    C
Name: label, dtype: object

In [7]:
df1['label'].str.lower()

0    a
1    b
2    c
3    a
4    b
5    c
Name: label, dtype: object

In [8]:
df1['value'].sum()

np.int64(21)

In [9]:
# Apply aggregates across numerical entries:
dfgb = df1.groupby('label').sum()
dfgb

       value
label
A          5
B          7
C          9

In [10]:
# more complex data types

s1 = 1
s2 = pd.Timestamp('20130102')
s3 = pd.Series(1,index=list(range(4)),dtype='float32')
s4 = np.arange(0,4) # one range
s5 = pd.Categorical(["test","train","test","train"])
s6 = 'foo'
dates = pd.date_range('20130101', periods=4)

In [11]:
dict1 = {'A' : s1,
         'B' : s2,
         'C' : s3,
         'D' : s4,
         'E' : s5,
         'F' : s6 }
print(dict1)

{'A': 1, 'B': Timestamp('2013-01-02 00:00:00'), 'C': 0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32, 'D': array([0, 1, 2, 3]), 'E': ['test', 'train', 'test', 'train']
Categories (2, object): ['test', 'train'], 'F': 'foo'}

In [12]:
# Convert to a pandas dataframe
df2 = pd.DataFrame(dict1,        #the dictionary is the data
                   index=dates)  #the dates will become the elements of the first column,
                                 #i.e. the index
df2 #Something missing??

            A          B   C  D      E    F
2013-01-01  1 2013-01-02 NaN  0   test  foo
2013-01-02  1 2013-01-02 NaN  1  train  foo
2013-01-03  1 2013-01-02 NaN  2   test  foo
2013-01-04  1 2013-01-02 NaN  3  train  foo

In [13]:
df2.dtypes # "df" is the name of the dataframe;

A            int64
B    datetime64[s]
C          float32
D            int64
E         category
F           object
dtype: object

In [14]:
df2 = df2.rename(columns = {'F':'hahahah'})
df2

            A          B   C  D      E hahahah
2013-01-01  1 2013-01-02 NaN  0   test     foo
2013-01-02  1 2013-01-02 NaN  1  train     foo
2013-01-03  1 2013-01-02 NaN  2   test     foo
2013-01-04  1 2013-01-02 NaN  3  train     foo

In [15]:
df2.describe() # Only numerical columns

         A                    B    C         D
count  4.0                    4  0.0  4.000000
mean   1.0  2013-01-02 00:00:00  NaN  1.500000
min    1.0  2013-01-02 00:00:00  NaN  0.000000
25%    1.0  2013-01-02 00:00:00  NaN  0.750000
50%    1.0  2013-01-02 00:00:00  NaN  1.500000
75%    1.0  2013-01-02 00:00:00  NaN  2.250000
max    1.0  2013-01-02 00:00:00  NaN  3.000000
std    0.0                  NaN  NaN  1.290994

In [16]:
df2.info() #Important for data exploration

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4 entries, 2013-01-01 to 2013-01-04
Freq: D
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   A        4 non-null      int64
 1   B        4 non-null      datetime64[s]
 2   C        0 non-null      float32
 3   D        4 non-null      int64
 4   E        4 non-null      category
 5   hahahah  4 non-null      object
dtypes: category(1), datetime64[s](1), float32(1), int64(2), object(1)
memory usage: 304.0+ bytes

# Part 2: An example: The stock market

Data source: https://www.nasdaq.com/symbol/csv/historical

## Importing "CSV" data

In [17]:
# Install the library on your environment
import sys
!{sys.executable} -m pip install wget

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9686 sha256=bc567cbe30943d9f03defd9d50906a37aac3ce2bd31b112e24a6d0e9202e45a1
  Stored in directory: /root/.cache/pip/wheels/8a/b8/04/0c88fb22489b0c049bee4e977c5689c7fe597d6c4b0e7d0b6a
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

In [18]:
# Mount and setup the Google Drive path
from google.colab import drive
drivePath = '/content/drive' #please do not change
drive.mount(drivePath)

Mounted at /content/drive

In [19]:
# Import the library
import wget

# Setup URL and path variables
baseURL = 'https://raw.githubusercontent.com/pmengoni/AIDM7330-2223S1/main/'
doc = 'HistoricalQuotes_2008-2018_googl.csv'
fullURL = baseURL + doc

dataPath = drivePath + '/MyDrive/Colab Notebooks/data'

# Download the file
fileName = wget.download(fullURL, out=dataPath)

# Print the file name including the local path
print(fileName)

/content/drive/MyDrive/Colab Notebooks/data/HistoricalQuotes_2008-2018_googl (1).csv

In [20]:
### We can download data from the web by using pd.read_csv
# A CSV file is a comma seperated file
# We can use this 'pd.read_csv' method with urls that host csv files

# source: https://www.nasdaq.com/symbol/csv/historical

dfg = pd.read_csv(fileName)

In [21]:
print(type(dfg))
dfg.head(10) # show first n values

<class 'pandas.core.frame.DataFrame'>

        date  close   volume   open    high      low
0  9/19/2018  22.10  142,544  22.20  22.420  22.0000
1  9/18/2018  22.10   140735  22.15  22.420  22.0000
2  9/17/2018  22.16    54893  22.43  22.565  22.1500
3  9/14/2018  22.43    59536  22.29  22.560  22.2300
4  9/13/2018  22.29    61342  22.43  22.670  22.2500
5  9/12/2018  22.40   102361  22.53  22.680  22.1500
6  9/11/2018  22.58   108116  22.31  22.630  22.2000
7  9/10/2018  22.37    89903  22.75  22.800  22.1900
8   9/7/2018  22.65   104034  22.37  22.770  22.2300
9   9/6/2018  22.40    87539  22.46  22.460  22.2676

In [22]:
dfg.tail(5) # last three

           date  close  volume  open    high   low
2514  9/24/2008   3.28  129769  3.46  3.5800  3.26
2515  9/23/2008   3.48  264652  3.45  3.7500  3.36
2516  9/22/2008   3.41  231344  3.36  3.4600  3.30
2517  9/19/2008   3.30  251526  3.31  3.6717  3.20
2518  9/18/2008   3.30  126877  3.40  3.4500  3.27

In [23]:
dfg.columns # returns columns, can be used to loop over

Index(['date', 'close', 'volume', 'open', 'high', 'low'], dtype='object')

In [24]:
#select one column at a time
for column in dfg.columns:
    print(column)
    print(dfg[column].head(2))

date
0    9/19/2018
1    9/18/2018
Name: date, dtype: object
close
0    22.1
1    22.1
Name: close, dtype: float64
volume
0    142,544
1     140735
Name: volume, dtype: object
open
0    22.20
1    22.15
Name: open, dtype: float64
high
0    22.42
1    22.42
Name: high, dtype: float64
low
0    22.0
1    22.0
Name: low, dtype: float64

In [25]:
dfg.index # return

RangeIndex(start=0, stop=2519, step=1)

In [26]:
dfg.describe()

            close         open         high          low
count  2519.00000  2519.000000  2519.000000  2519.000000
mean     15.01947    15.013484    15.205141    14.826368
std       8.99902     9.003459     9.078259     8.928512
min       1.41000     1.380000     1.470000     1.100000
25%       5.46000     5.440000     5.530050     5.345000
50%      17.77000    17.750000    18.030000    17.500000
75%      23.62000    23.600000    23.850000    23.388800
max      28.93000    29.000000    29.110000    28.840000

## Convert the index to pandas datetime object

In [27]:
type(dfg['date'][0])

str

In [28]:
#First way
#Convert and set index
dfg2=dfg
#Convert
dfg2 = dfg.copy() #let's make a copy first
dfg2['date'] = pd.to_datetime(dfg2['date']) #convert to datetime, can specify format = '%d%b%Y:%H:%M:%S.%f'
type(dfg2['date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [29]:
#Set index
#Careful: no undo
dfg2.set_index('date', inplace=True) #set the index
dfg2.head()

            close   volume   open    high    low
date
2018-09-19  22.10  142,544  22.20  22.420  22.00
2018-09-18  22.10   140735  22.15  22.420  22.00
2018-09-17  22.16    54893  22.43  22.565  22.15
2018-09-14  22.43    59536  22.29  22.560  22.23
2018-09-13  22.29    61342  22.43  22.670  22.25

In [30]:
dfg.head(2)

        date  close   volume   open   high   low
0  9/19/2018   22.1  142,544  22.20  22.42  22.0
1  9/18/2018   22.1   140735  22.15  22.42  22.0

In [31]:
print(type(dfg2.index[0]))
dfg2.index[0]

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

Timestamp('2018-09-19 00:00:00')

In [32]:
#Second way
#Convert and copy to index
dfg.index = pd.to_datetime(dfg['date'])

In [33]:
dfg.head(1)

                 date  close   volume  open   high   low
date
2018-09-19  9/19/2018   22.1  142,544  22.2  22.42  22.0

In [34]:
#Remove duplicated column
#Careful: no undo
dfg.drop(['date'],axis=1,inplace=True)

In [35]:
dfg.head(10)

            close   volume   open    high      low
date
2018-09-19  22.10  142,544  22.20  22.420  22.0000
2018-09-18  22.10   140735  22.15  22.420  22.0000
2018-09-17  22.16    54893  22.43  22.565  22.1500
2018-09-14  22.43    59536  22.29  22.560  22.2300
2018-09-13  22.29    61342  22.43  22.670  22.2500
2018-09-12  22.40   102361  22.53  22.680  22.1500
2018-09-11  22.58   108116  22.31  22.630  22.2000
2018-09-10  22.37    89903  22.75  22.800  22.1900
2018-09-07  22.65   104034  22.37  22.770  22.2300
2018-09-06  22.40    87539  22.46  22.460  22.2676

In [36]:
print(type(dfg.index[0]))
dfg.index[0]

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

Timestamp('2018-09-19 00:00:00')

In [37]:
# We can query date indices with strings
# Order Dataframe by index
dfg.sort_index(inplace=True)

In [38]:
#To extract a single element we need to use .loc
dfg.loc['2018-09-10']

close     22.37
volume    89903
open      22.75
high       22.8
low       22.19
Name: 2018-09-10 00:00:00, dtype: object

In [39]:
# to extract a range we can use slicing
dfg['2018-09-10':'2018-09-15']

            close  volume   open   high    low
date
2018-09-10  22.37   89903  22.75  22.80  22.19
2018-09-11  22.58  108116  22.31  22.63  22.20
2018-09-12  22.40  102361  22.53  22.68  22.15
2018-09-13  22.29   61342  22.43  22.67  22.25
2018-09-14  22.43   59536  22.29  22.56  22.23

## Attributes & general statitics of a Pandas DataFrame

In [40]:
dfg.shape # 2519 business days in the past 10 years, 5 variables

(2519, 5)

In [41]:
dfg.shape[1]

5

In [42]:
dfg.size

12595

In [43]:
dfg.columns

Index(['close', 'volume', 'open', 'high', 'low'], dtype='object')

In [44]:
# Some general statistics

dfg.describe()

            close         open         high          low
count  2519.00000  2519.000000  2519.000000  2519.000000
mean     15.01947    15.013484    15.205141    14.826368
std       8.99902     9.003459     9.078259     8.928512
min       1.41000     1.380000     1.470000     1.100000
25%       5.46000     5.440000     5.530050     5.345000
50%      17.77000    17.750000    18.030000    17.500000
75%      23.62000    23.600000    23.850000    23.388800
max      28.93000    29.000000    29.110000    28.840000

In [45]:
dfg['open']>15

date
2008-09-18    False
2008-09-19    False
2008-09-22    False
2008-09-23    False
2008-09-24    False
              ...
2018-09-13     True
2018-09-14     True
2018-09-17     True
2018-09-18     True
2018-09-19     True
Name: open, Length: 2519, dtype: bool

In [46]:
dfg[dfg['open']>15]

            close   volume   open    high    low
date
2013-02-14  15.24    37109  15.09  15.280  14.98
2013-02-15  15.67    83689  15.30  15.730  15.25
2013-02-19  16.28   234577  15.70  16.460  15.70
2013-02-20  15.41   151377  16.34  16.380  15.40
2013-02-21  15.39    64728  15.38  15.640  15.00
...           ...      ...    ...     ...    ...
2018-09-13  22.29    61342  22.43  22.670  22.25
2018-09-14  22.43    59536  22.29  22.560  22.23
2018-09-17  22.16    54893  22.43  22.565  22.15
2018-09-18  22.10   140735  22.15  22.420  22.00
2018-09-19  22.10  142,544  22.20  22.420  22.00

[1410 rows x 5 columns]

In [47]:
# Boolean indexing
dfg['open'][dfg['open']>15]  # check what dates the opening > 15

date
2013-02-14    15.09
2013-02-15    15.30
2013-02-19    15.70
2013-02-20    16.34
2013-02-21    15.38
              ...
2018-09-13    22.43
2018-09-14    22.29
2018-09-17    22.43
2018-09-18    22.15
2018-09-19    22.20
Name: open, Length: 1410, dtype: float64

In [48]:
dfg['open'][dfg['open']>15].head(5)  # check what dates the opening with the firt 5

date
2013-02-14    15.09
2013-02-15    15.30
2013-02-19    15.70
2013-02-20    16.34
2013-02-21    15.38
Name: open, dtype: float64

In [49]:
# Check where Open, High, Low and Close where greater than a specified value
dfg[dfg.open>20].head(3)

            close  volume   open   high      low
date
2013-03-21  20.38  216349  20.20  20.71  20.2000
2013-03-22  20.15  199252  20.39  20.60  20.1000
2013-03-25  20.76  237140  20.46  20.87  20.3015

In [50]:
dfg.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2519 entries, 2008-09-18 to 2018-09-19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   close   2519 non-null   float64
 1   volume  2519 non-null   object
 2   open    2519 non-null   float64
 3   high    2519 non-null   float64
 4   low     2519 non-null   float64
dtypes: float64(4), object(1)
memory usage: 182.6+ KB

In [ ]:
# drop na - not run for now
# Comments on dropping and filling NaN values
# A view where we drop any rows with value NaN
# dfg.dropna(how='any')  # this would be used to drop rows with NaN
# dfg.fillna(value=5)    # this would be used to fill NaN values with 5

In [51]:
# If you want the values in an np array
npg = dfg.values
print(type(npg))
print(npg)

<class 'numpy.ndarray'>
[[3.3 '126877' 3.4 3.45 3.27]
 [3.3 '251526' 3.31 3.6717 3.2]
 [3.41 '231344' 3.36 3.46 3.3]
 ...
 [22.16 '54893' 22.43 22.565 22.15]
 [22.1 '140735' 22.15 22.42 22.0]
 [22.1 '142,544' 22.2 22.42 22.0]]

## Selecting or Viewing Data within a DataFrame
Note: While standard Python / Numpy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, .at, .iat, .loc, .iloc and .ix. (from 10 min guide to Pandas)

In [52]:
# Lets print the five first Close prices for Google
# This is a new Series (like a new table)
dfg['close'][0:5]

date
2008-09-18    3.30
2008-09-19    3.30
2008-09-22    3.41
2008-09-23    3.48
2008-09-24    3.28
Name: close, dtype: float64

In [53]:
# Lets print the 3 column
dfg[['close','open','volume']][0:7]

            close  open  volume
date
2008-09-18   3.30  3.40  126877
2008-09-19   3.30  3.31  251526
2008-09-22   3.41  3.36  231344
2008-09-23   3.48  3.45  264652
2008-09-24   3.28  3.46  129769
2008-09-25   3.37  3.30  126197
2008-09-26   3.42  3.46   62560

In [54]:
# A slice: by rows (row numbers)
dfg[1:5] # 2nd to 5th element

            close  volume  open    high   low
date
2008-09-19   3.30  251526  3.31  3.6717  3.20
2008-09-22   3.41  231344  3.36  3.4600  3.30
2008-09-23   3.48  264652  3.45  3.7500  3.36
2008-09-24   3.28  129769  3.46  3.5800  3.26

In [55]:
# As in lists
list1 = [0,1,2,3,4]
list1[1:5]

[1, 2, 3, 4]

## .loc()

In [56]:
# Getting a cross section with .loc - BY VALUES of the index and columns
# df.loc[a:b, x:y], by rows and column location

# Note: You have to know indices and columns

dfg.loc['2019-08-21':'2019-08-31',
        'open':'low']

Empty DataFrame
Columns: [open, high, low]
Index: []

## .iloc()

In [57]:
dfg.columns

Index(['close', 'volume', 'open', 'high', 'low'], dtype='object')

In [58]:
# .iloc slicing at specific location - BY POSITION in the table
# Recall:
# dfg[a:b] by rows
# dfg[[col]] or df[[col1, col2]] by columns
# df.loc[a:b, x:y], by index and column values + location
# df.iloc[3:5,0:2], numeric position in table

dfg.iloc[1:4,3:5] # 2nd to 4th row, 4th to 5th column

              high   low
date
2008-09-19  3.6717  3.20
2008-09-22  3.4600  3.30
2008-09-23  3.7500  3.36

In [59]:
# Data only from row with index value '3'
print (dfg.iloc[3])

close       3.48
volume    264652
open        3.45
high        3.75
low         3.36
Name: 2008-09-23 00:00:00, dtype: object

In [60]:
# iloc will accept a range with ':', just like numpy
# : means "all"
dfg.iloc[1:3,:]

            close  volume  open    high  low
date
2008-09-19   3.30  251526  3.31  3.6717  3.2
2008-09-22   3.41  231344  3.36  3.4600  3.3

In [61]:
# Can also return specific value
print (dfg.iloc[2,1])
# same as above but faster for one single scalar value
print (dfg.iat[2,1])

231344
231344

## More Basic Statistics

In [62]:
# A quick way to get statistics
dfg.describe()

            close         open         high          low
count  2519.00000  2519.000000  2519.000000  2519.000000
mean     15.01947    15.013484    15.205141    14.826368
std       8.99902     9.003459     9.078259     8.928512
min       1.41000     1.380000     1.470000     1.100000
25%       5.46000     5.440000     5.530050     5.345000
50%      17.77000    17.750000    18.030000    17.500000
75%      23.62000    23.600000    23.850000    23.388800
max      28.93000    29.000000    29.110000    28.840000

The result of describe is a DataFrame, so you can access and slice like a normal DataFrame

In [63]:
dfg.describe()['open'][1]

/tmp/ipykernel_1580/364102089.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dfg.describe()['open'][1]

np.float64(15.013483604605002)

In [64]:
dfg.describe()[1:3]

         close       open       high        low
mean  15.01947  15.013484  15.205141  14.826368
std    8.99902   9.003459   9.078259   8.928512

In [65]:
dfg.describe().loc[['mean','std'],['high','low']]

           high        low
mean  15.205141  14.826368
std    9.078259   8.928512

In [66]:
dfg.head()

            close  volume  open    high   low
date
2008-09-18   3.30  126877  3.40  3.4500  3.27
2008-09-19   3.30  251526  3.31  3.6717  3.20
2008-09-22   3.41  231344  3.36  3.4600  3.30
2008-09-23   3.48  264652  3.45  3.7500  3.36
2008-09-24   3.28  129769  3.46  3.5800  3.26

In [67]:
# We can change the index sorting
# Not in place, should specify inplace=True to record it
dfg.sort_index(axis=0, ascending=False).head()

#Short for:
##dfg.sort_index(axis=0, ascending=True)
##dfg.head()

            close   volume   open    high    low
date
2018-09-19  22.10  142,544  22.20  22.420  22.00
2018-09-18  22.10   140735  22.15  22.420  22.00
2018-09-17  22.16    54893  22.43  22.565  22.15
2018-09-14  22.43    59536  22.29  22.560  22.23
2018-09-13  22.29    61342  22.43  22.670  22.25

In [68]:
# The dataframe didn't change
dfg.head(3)

            close  volume  open    high   low
date
2008-09-18   3.30  126877  3.40  3.4500  3.27
2008-09-19   3.30  251526  3.31  3.6717  3.20
2008-09-22   3.41  231344  3.36  3.4600  3.30

In [69]:
# sort by value
dfg.sort_values(by='open', ascending=True)[0:10]

            close  volume  open    high    low
date
2009-03-24   1.50   39300  1.38  1.5100  1.380
2009-03-20   1.45   76175  1.41  1.4700  1.400
2009-03-23   1.47  137700  1.42  1.5250  1.420
2009-03-19   1.41  189240  1.43  1.4800  1.365
2009-04-01   1.59  144192  1.49  1.5900  1.490
2009-03-13   1.52   83325  1.49  1.5700  1.490
2009-03-25   1.49   30926  1.49  1.5200  1.490
2009-03-16   1.51   66174  1.50  1.5300  1.500
2009-03-18   1.49   26360  1.50  1.5300  1.490
2009-03-12   1.49  157672  1.50  1.5464  1.490

## Masks and Boolean Indexing

In [70]:
dfg[0:10]

            close  volume  open    high   low
date
2008-09-18   3.30  126877  3.40  3.4500  3.27
2008-09-19   3.30  251526  3.31  3.6717  3.20
2008-09-22   3.41  231344  3.36  3.4600  3.30
2008-09-23   3.48  264652  3.45  3.7500  3.36
2008-09-24   3.28  129769  3.46  3.5800  3.26
2008-09-25   3.37  126197  3.30  3.4800  3.28
2008-09-26   3.42   62560  3.46  3.5000  3.25
2008-09-29   3.95   88871  3.43  4.1340  3.20
2008-09-30   3.50  111006  4.00  4.0500  3.35
2008-10-01   3.55  155579  3.59  3.6700  3.41

In [71]:
# mask 1
mg1 = dfg['open'][0:10]>3.40
print (mg1)

date
2008-09-18    False
2008-09-19    False
2008-09-22    False
2008-09-23     True
2008-09-24     True
2008-09-25    False
2008-09-26     True
2008-09-29     True
2008-09-30     True
2008-10-01     True
Name: open, dtype: bool

In [72]:
dfg['open'][0:10][dfg['open']>3.40]
# shows only rows with opening price greater than 22.40

date
2008-09-23    3.45
2008-09-24    3.46
2008-09-26    3.46
2008-09-29    3.43
2008-09-30    4.00
2008-10-01    3.59
Name: open, dtype: float64

In [ ]:
# mask 2 full data frame - only if the dataframe columns are allo the same type
# mg2 = dfg[0:10]>22.50
# mg2

In [ ]:
#dfg[dfg>22.50].head(10)

In [ ]:
# we can also drop all NaN values
#dfg[dfg>22.50].head(10).dropna()

In [73]:
# like Numpy, sometimes you need an actual copy, not a view or slice of the same data
# any operation done on dfg or dfg_same is reflected on the other
dfg_same = dfg
dfg_same is dfg

True

In [74]:
# Now we create a second copy of the dataframe, they will be independent from each other
dfg2 = dfg.copy()
dfg2 is dfg

False

# Aknowledgements

- The codes in this notebook are modified from various sources including Dr. Xinzhi Zhang Jupyter notebooks.
- All codes are for educational purposes only and released under the CC1.0.